Вывод категорий и товаров
htmlacademy-php/1967715-yeticave-12 pull request #3
Opened 2022-01-30 13:28 UTC by zarjik-web

Итерация по массивам

2022-01-30 13:45 UTC, tagedo requested changes
Замени, пожалуйста, while на foreach
В остальном все хорошо!

2022-01-30 13:45 UTC, tagedo commented on index.php
> +          <?php while($numbers < 6): ?>
Азат, здесь тоже удобнее foreach - меньше действий, переменных.

2022-01-31 17:59 UTC, zarjik-web reviewed
Исправил

2022-01-31 21:58 UTC, tagedo approved these changes
Все правильно!

2022-01-31 22:33 UTC, tagedo approved these changes

2022-01-31 22:35 UTC, tagedo approved these changes

2022-02-01 18:52 UTC, merged