Пишем первую функцию
htmlacademy-php/1967715-yeticave-12 pull request #4
Opened 2022-02-13 18:28 UTC by zarjik-web

Пишем первую функцию

2022-02-13 21:26 UTC, tagedo requested changes
Азат, нужно немного подправить и будет хорошо)

2022-02-13 21:26 UTC, tagedo commented on index.php
> +    return $result . '<b class="rub">р</b>';
не добавлен пробел, а буква Р не нужна, здесь фоновое изображение

2022-02-13 21:26 UTC, tagedo commented on index.php
> +        $decimals,
можно для параметров не создавать переменных, а сразу указывать значения - но это как тебе удобнее

2022-02-13 21:26 UTC, tagedo commented on index.php
> -                            <span class="lot__amount">Стартовая цена</span>
эта строчка не должна пропасть

2022-02-16 19:27 UTC, zarjik-web reviewed
Правки

2022-02-16 19:49 UTC, tagedo approved these changes
Все хорошо.

2022-02-16 19:50 UTC, merged